-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 22:19:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `bdcamas` DEFAULT CHARACTER SET utf8 ;
USE `bdcamas` ;

-- -----------------------------------------------------
-- Table `bdcamas`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bdcamas`.`EstadosProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`EstadosProducto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bdcamas`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(245) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(245) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `ruc` VARCHAR(11) NOT NULL unique,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precioCompra` DOUBLE NOT NULL,
  `precioVenta` DOUBLE NOT NULL,
  `idCategoria` INT NOT NULL,
  `idEstado` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Productos_Categorias_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_Productos_EstadosProducto1_idx` (`idEstado` ASC) VISIBLE,
  INDEX `fk_Productos_Proveedores1_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdcamas`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_EstadosProducto1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `bdcamas`.`EstadosProducto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `bdcamas`.`Proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `img` TEXT NULL,
  `esPrincipal` BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (`id`),
    CONSTRAINT `fk_Productos_IMAGEN`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdcamas`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bdcamas`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`EstadosEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`EstadosEmpleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` CHAR(10) NOT NULL,
  `nombres` VARCHAR(245) NOT NULL,
  `apePaterno` VARCHAR(245) NOT NULL,
  `apeMaterno` VARCHAR(245) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contra` VARCHAR(245) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `idRol` INT NOT NULL,
  `idEstado` INT NOT NULL, 
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuarios_Roles1_idx` (`idRol` ASC) VISIBLE,
  INDEX `fk_Usuarios_EstadosUsuario1_idx` (`idEstado` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Roles1`
    FOREIGN KEY (`idRol`)
    REFERENCES `bdcamas`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_EstadosUsuario1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `bdcamas`.`EstadosEmpleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CREATE TABLE bdcamas.SessionesActivas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idEmpleado INT NOT NULL,
    ip VARCHAR(45) NOT NULL,
    token VARCHAR(255) NOT NULL,
    usuarioModificador VARCHAR(100),
    fechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fechaModificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idEmpleado) REFERENCES Empleados(id) ON DELETE CASCADE
);
  CREATE TABLE IF NOT EXISTS `bdcamas`.`IntentosSession` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` int NOT NULL,
  `ip` varchar(20) NOT NULL,
  `cantidad` int NOT NULL,
  `fecha` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hora` time NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE ,
    CONSTRAINT `fk_Usuarios_Session1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `bdcamas`.`Empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `bdcamas`.`HistorialSesion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `ip`VARCHAR(15) NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
CONSTRAINT `fk_Usuarios_Session`
FOREIGN KEY (`idEmpleado`)
REFERENCES `bdcamas`.`Empleados` (`id`)
ON DELETE CASCADE
ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `bdcamas`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `ubicacion` VARCHAR(245) NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_Productos1_idx` (`idProducto` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdcamas`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(245) NOT NULL,
  `apePaterno` VARCHAR(245) NOT NULL,
  `apeMaterno` VARCHAR(245) NOT NULL,
  `dni` VARCHAR(10) NULL,
  `telefono` VARCHAR(9) NULL,
  `correo` VARCHAR(100) NULL,
  `contra` VARCHAR(245) NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bdcamas`.`MetodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`MetodoPago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(145) NOT NULL,
  `descripcion` VARCHAR(245) NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`TipoComprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`TipoComprobante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(145) NOT NULL,
  `descripcion` VARCHAR(245) NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Comprobante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE  NOT NULL,
  `hora` TIME  NOT NULL ,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  `idTipoComprobante` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comprobante_TipoComprobante1_idx` (`idTipoComprobante` ASC) VISIBLE,
  CONSTRAINT `fk_Comprobante_TipoComprobante1`
    FOREIGN KEY (`idTipoComprobante`)
    REFERENCES `bdcamas`.`TipoComprobante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `impuesto` double null,
  `total` DOUBLE NULL,
  `descuento` DOUBLE NULL,
  `idMetodoPago` INT NOT NULL,
  `horaVenta` TIME  NOT NULL ,
  `idComprobante` INT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  INDEX `fk_Ventas_Clientes1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Ventas_Usuarios1_idx` (`idEmpleado` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Ventas_MetodoPago1_idx` (`idMetodoPago` ASC) VISIBLE,
  INDEX `fk_Ventas_Comprobante1_idx` (`idComprobante` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdcamas`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Usuarios1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `bdcamas`.`Empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_MetodoPago1`
    FOREIGN KEY (`idMetodoPago`)
    REFERENCES `bdcamas`.`MetodoPago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Comprobante1`
    FOREIGN KEY (`idComprobante`)
    REFERENCES `bdcamas`.`Comprobante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`DetallesVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`DetallesVenta` (
  `idVenta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  INDEX `fk_Detalles_Venta_Ventas1_idx` (`idVenta` ASC) VISIBLE,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_DetallesVenta_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Detalles_Venta_Ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `bdcamas`.`Ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallesVenta_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdcamas`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `direccion` TEXT NOT NULL,
  `distrito` TEXT NOT NULL,
  `referencia` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Direcciones_Clientes1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Direcciones_Clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdcamas`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`EstadosEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`EstadosEnvio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Transporte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(245) NOT NULL,
  `modelo` VARCHAR(245) NOT NULL,
  `marca` VARCHAR(245) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Envios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `idTransporte` INT NOT NULL,
  `idVenta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `horaEntrega` TIME  NOT NULL ,
  `horaSalida` TIME  NOT NULL ,
  `idEstadoEnvio` INT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Envios_Usuarios1_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Envios_Ventas1_idx` (`idVenta` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Envios_EstadosEnvio1_idx` (`idEstadoEnvio` ASC) VISIBLE,
  INDEX `fk_Envios_Transporte1_idx` (`idTransporte` ASC) VISIBLE,
  CONSTRAINT `fk_Envios_Usuarios1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `bdcamas`.`Empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `bdcamas`.`Ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_EstadosEnvio1`
    FOREIGN KEY (`idEstadoEnvio`)
    REFERENCES `bdcamas`.`EstadosEnvio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Transporte1`
    FOREIGN KEY (`idTransporte`)
    REFERENCES `bdcamas`.`Transporte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`EstadosCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`EstadosCompra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` VARCHAR(245) NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`ProveedorContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`ProveedorContacto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `idProveedor` INT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProveedorContacto_Proveedores1_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_ProveedorContacto_Proveedores1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `bdcamas`.`Proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`Compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DOUBLE NULL,
  `idEmpleado` INT NOT NULL,
  `idEstadoCompra` INT NOT NULL,
  `idProveedor` INT UNSIGNED NOT NULL,
  `horaCompra` TIME  NOT NULL ,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  `idComprobante` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Compras_Usuarios1_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Compras_Estado1_idx` (`idEstadoCompra` ASC) VISIBLE,
  INDEX `fk_Compras_ProveedorContacto1_idx` (`idProveedor` ASC) VISIBLE,
  INDEX `fk_Compras_Comprobante1_idx` (`idComprobante` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Usuarios1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `bdcamas`.`Empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Estado1`
    FOREIGN KEY (`idEstadoCompra`)
    REFERENCES `bdcamas`.`EstadosCompra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_ProveedorContacto1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `bdcamas`.`ProveedorContacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Comprobante1`
    FOREIGN KEY (`idComprobante`)
    REFERENCES `bdcamas`.`Comprobante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcamas`.`DetallesCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcamas`.`DetallesCompra` (
  `idCompra` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioCreador` INT NOT NULL,
  `fechaModificación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarioModificador` INT NOT NULL,
  INDEX `fk_DetalllesCompra_Productos1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_DetallesCompra_Compras1_idx` (`idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_DetalllesCompra_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdcamas`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallesCompra_Compras1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `bdcamas`.`Compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


